# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ChiaLinks - Chia Cryptocurrency Resources
email: chialinks@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  ChiaLinks is a curated collection of resources from around the web for all things related to the Chia cryptocurrency (XCH) -- green money for a digital world.
baseurl: "/chialinks" # the subpath of your site, e.g. /blog
#url: "http://127.0.0.1:4000" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://chialinks.com" # for prod
twitter_username:
github_username:

# Build settings
remote-theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/chialinks_logo2.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Aux links for the upper right navigation
aux_links:
  - title: Get Started
    icon: chia
    url: /get-started/
    new_tab: false
  - title: Chia NFTs
    icon: nfts
    url: /get-started-chia-nfts/
    new_tab: false
  - title: F.A.Q.
    icon: faq
    url: /faq/
    new_tab: false
  - title: Updates
    icon: updates
    url: /updates/
    new_tab: false
  - title: News
    icon: news
    url: /news/
    new_tab: false
  - title: Roadmap
    icon: guides
    url: /roadmap/
    new_tab: false
  - title: Ecosystem
    icon: get-started
    url: /ecosystem/
    new_tab: false
  - title: Submit Link
    icon: submit
    url: /submit/
    new_tab: false

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; ChiaLinks.com 2021-2023. Icons made by <a href='https://www.flaticon.com/authors/baianat'>Baianat</a> from <a href='https://www.flaticon.com' target='_blank'>www.flaticon.com</a>.<br /> CHIA NETWORK INC and CHIA&#8482; are registered trademarks or trademarks of Chia Network, Inc. in the United States and worldwide."

# Footer last edited timestamp
last_edit_timestamp: false # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-194893128-1
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
